### ISSUE TITLE
Pyscf does not work in parallel

### ISSUE THREAD

**Issue by mkrompiec** [RagnarB83/ash#364]
NEB(runmode='parallel') doesn't work with the PySCF interface:
```
Terminating Pool processes due to exception 
 Exception message: cannot pickle 'module' object
```

**Comment by RagnarB83** [comment]
Thanks for reporting, this is an unfortunate limitation of the  simple multiprocessing parallelization strategy employed. I need to think about how to get around this one as supporting pyscf here would be useful.

**Comment by mkrompiec** [comment]
Thanks, it would be great if this could be fixed. Thanks for making Ash publicly available!

**Comment by mkrompiec** [comment]
@RagnarB83 , I am almost sure the culprit is the load_pyscf function and the fact that self.pyscf is a module. Removing this seems to rectify the error (the code doesn't immediately crash, but I'm not sure yet if it runs correctly).

**Comment by RagnarB83** [comment]
You are right. Wrapping the whole pyscf library into the PySCFTheory class makes the object unpicklable and prevents multiprocessing parallelization from working.
While I was aware of this, I thought there would be other pickle-issues that would also prevent the pyscf interface from working together with multiprocessing.
But this seems to be enough. Thanks for the help!

I have committed a new PySCF interface on the NEW branch that avoids this in retrospect silly wrapping. This currently will break other functionality of the interface,  that will require fixing but having multiprocessing work with PySCF is definitely worth it.

Further testing of parallel NEB with pyscf is required

**Comment by mkrompiec** [comment]
thanks!

**Comment by RagnarB83** [comment]
After some testing it seems things are overall working. It seems one can even utilize the PySCF threading (controlled by PySCFTheory(numcores))  simultaneously.

 Setting export OMP_NUM_THREADS=1 in the jobscript was, however, necessary  for the latter to work on my cluster, otherwise the pyscf  threading could not be controlled reliably by ASH. Closing this issue soon unless there are other issues.
