### ISSUE TITLE
Add dispersion corrections to PySCF interface

### ISSUE THREAD

**Issue by mkrompiec** [RagnarB83/ash#365]
For example via https://github.com/ajz34/vdw ?

**Comment by RagnarB83** [comment]
It's a good idea, did not even realize that there are no dispersion corrections in PySCF by default.
I have done a very quick implementation of this library in branch NEW.
Should work when providing dispersion keyword to PySCFTheory.
Options are: 'D3', 'D4', 'TS' and 'MBD'.

Needs to be tested

**Comment by mkrompiec** [comment]
Awesome, thanks!
