### ISSUE TITLE
PySCF interface: newton converger

### ISSUE THREAD

**Issue by mkrompiec** [RagnarB83/ash#369]
In many cases, the default DIIS converger in PySCF is poor and often the newton method is more efficient (although each SCF iteration takes much longer). It would be great to have an optional parameter to enable the newton method.
In my local branch, I have this just after` if self.functional is not None`: (because mf.newton() must be called after setting mf.xc)
```
        if self.newton:
            self.mf=self.mf.newton()
```

**Comment by RagnarB83** [comment]
Good point, I'll add it

**Comment by RagnarB83** [comment]
Added (used soscf keyword instead).
Also added other convergence aid options:
guess='minao', soscf=False, damping=None, diis_method='DIIS', diis_start_cycle=0, level_shift=None, fractional_occupation=False,

**Comment by RagnarB83** [comment]
Done: scf_maxiter

**Comment by RagnarB83** [comment]
closed
