### ISSUE TITLE
geomeTRIC Attribute error

### ISSUE THREAD

**Issue by erfantoloue** [RagnarB83/ash#373]
Dear Dr. Bjornsson,

Thank you very much for developing this valuable tool. I came across this error while working on a QM/MM optimization. It would mean a lot if you help me out on this one.

<class 'geometric.internal.Angle'> : 105
<class 'geometric.internal.OutOfPlane'> : 17
<class 'geometric.internal.Dihedral'> : 167
Traceback (most recent call last):
  File "/home/ahmad/dr.kalhor/erfan/qmmm_try1/qmmm_opt_1.py", line 59, in <module>
    geomeTRICOptimizer(theory=qmmmobject, fragment=frag, ActiveRegion=True, actatoms=qmatoms, maxiter=500, charge=charge,mult=mult,coordsystem='dlc')
  File "/home/reza/Desktop/ash/interfaces/interface_geometric.py", line 29, in geomeTRICOptimizer
    finalenergy = optimizer.run()
  File "/home/reza/Desktop/ash/interfaces/interface_geometric.py", line 318, in run
    self.geometric.optimize.run_optimizer(**vars(self.final_geometric_args))
  File "/home/reza/anaconda3/envs/ash/lib/python3.9/site-packages/geometric/optimize.py", line 923, in run_optimizer
    if engine.detect_dft() and coordsys != "dlc" and len(IC.frags) == 1:
AttributeError: 'ASHengineclass' object has no attribute 'detect_dft'

![Screenshot from 2023-05-08 23-03-09](https://user-images.githubusercontent.com/73541346/236921419-f6f852f0-6ee4-44f2-87aa-effc288a5457.png)

**Comment by RagnarB83** [comment]
That's a bit surprising. The detect_dft attribute has been present in the code for a long time. Any chance this is an old version of ASH?

The master branch of ASH was just updated with considerable general improvements. Can you try to get the new version and try again ?

**Comment by erfantoloue** [comment]
It looks like its ASH V0.9dev. I took the files right from your Github.

![image](https://github.com/RagnarB83/ash/assets/73541346/3aa6ecd0-c5d1-4c23-85da-26a6ebe4c0fc)

**Comment by RagnarB83** [comment]
Update the code and try again. Must have been a bug in the master version before the big update.

**Comment by RagnarB83** [comment]
Is the problem solved?

**Comment by erfantoloue** [comment]
I will let you know as soon as possible.

**Comment by erfantoloue** [comment]
Dear Dr. Bjornsson,

I am sorry for the late reply. I reinstalled ASH and I still got the same error.

`    geomeTRICOptimizer(theory=qmmmobject, fragment=frag, ActiveRegion=True, actatoms=qmatoms, maxiter=500, charge=charge,mult=mult,coordsystem='dlc')
  File "/home/erfantolou/Documents/ash/interfaces/interface_geometric.py", line 29, in geomeTRICOptimizer
    finalenergy = optimizer.run()
  File "/home/erfantolou/Documents/ash/interfaces/interface_geometric.py", line 318, in run
    self.geometric.optimize.run_optimizer(**vars(self.final_geometric_args))
  File "/home/erfantolou/conda/envs/Ash2/lib/python3.9/site-packages/geometric/optimize.py", line 923, in run_optimizer
    if engine.detect_dft() and coordsys != "dlc" and len(IC.frags) == 1:
AttributeError: 'ASHengineclass' object has no attribute 'detect_dft'
`
I have also attached my input files. I truly appreciate your help.

[Erfaninputfiles.zip](https://github.com/RagnarB83/ash/files/11575380/Erfaninputfiles.zip)

**Comment by RagnarB83** [comment]
I don't understand how this can happen if you have downloaded a recent version. The error says that ASHengineclass in the code does not have the attribute detect_dft but it absolutely does.


Can you send me the file:   /home/erfantolou/Documents/ash/interfaces/interface_geometric.py

**Comment by erfantoloue** [comment]
Wow! Thank you very much. It was somehow using the older version of Ash. I got the new version working and the error is gone. Thank you for your help!

**Comment by RagnarB83** [comment]
Good to hear!
