### ISSUE TITLE
A wrong message about XTB

### ISSUE THREAD

**Issue by kol0760** [RagnarB83/ash#379]
I encountered an error message when practicing **Metalloprotein tutorial I: Rubredoxin** .
> ModuleNotFoundError: No module named 'xtb

Then I modified the content of **3-QMMM_MD.py** and added "**runmode='library**'' as a workaround. However, a new error message appeared .

> 'Problem importing xTB library. Have you installed : conda install -c conda-forge xtb-python?' and ASH exited with code 9.

After installing xtb-python, I encountered a new problem with it.

> AttributeError: 'Results' object has no attribute 'get_PCgradient'. Did you mean: 'get_gradient'?

**Comment by RagnarB83** [comment]
Hi
Thanks for trying ASH out.

The first error was a bit of a bug in the interface (importing xtb python module should not be necessary for the default runmode) I just noticed. This has now been fixed.

When you switch to runmode='library' you then need to install xtb-python like you did which fixes the second error.

The third error comes from the fact that runmode='library' in xTBTheory is currently incompatible with QM/MM pointcharge-embedding. So you need to switch back to runmode='inputfile'.

The error messages have been improved. Hopefully I can enable xtb-library pointcharge embedding soon.
