### ISSUE TITLE
🧹  Cleanup files and structure

### ISSUE THREAD

**Issue by Anselmoo** [RagnarB83/ash#394]
- There are still some files left like `.DS_Store` or `__init__.pyc`, where it might sense to clean it up. 
- In addition to that, there should be only one `.gitignore`

An improvement would be to have a standalone `pre-commit` for removing whitespaces and trailing issues

**Comment by RagnarB83** [comment]
Thanks Anselm, will take a look

**Comment by RagnarB83** [comment]
Finally got around to look at this but had to do my own precommit. Thanks for pointing it out.
