### ISSUE TITLE
Relaxed scan results for a dihedral angle are unphysical

### ISSUE THREAD

**Issue by Lactoria-cornuta** [RagnarB83/ash#417]
Dear developers, 

I'm new to ASH, so I wanted to run some tests before diving into QM/MM. I calculated a relaxed scan for the torsion angle of ethane, which looked fine to me. However, when I calculated the relaxed scan for ethylene glycol (a symmetric molecule!) O-C-C-O torsion  I obtained unsymmetric potential energy profiles. I tried tweaking the "coordsystem" and "convergence_setting" options but it didn't help. What could be the problem and how to obtain the correct (symmetric) profile? 

My code:
mol = Fragment(pdbfile="Etgl.pdb", charge=0, mult=1)
xtb = xTBTheory(xtbmethod="GFN2", numcores=1, accuracy=0.1)
surf = calc_surface(theory=xtb, fragment=mol, scantype="Relaxed", resultfile='surf.txt', RC1_range=[-180,180,10], RC1_type='dihedral', RC1_indices=[9,0,1,8])
reactionprofile_plot(surf.surfacepoints, finalunit='kcal/mol',label='', x_axislabel='Angle', y_axislabel='Energy', imageformat='png', RelativeEnergy=True, pointsize=40, scatter_linewidth=2, line_linewidth=1, color='blue', filename="profile")

![profile](https://github.com/RagnarB83/ash/assets/72927172/84219666-5be1-40c1-8705-3ebbf43cdcf6)

My ethylene glycol geometry in pdb format:

HETATM    1  C01 UNK     1      -0.000  -0.000   0.000  0.00  0.00           C  
HETATM    2  C02 UNK     1       1.171   0.975  -0.220  0.00  0.00           C  
HETATM    3  H01 UNK     1       2.033   0.428  -0.600  0.00  0.00           H  
HETATM    4  H02 UNK     1       0.878   1.739  -0.941  0.00  0.00           H  
HETATM    5  H03 UNK     1       1.759   0.925   1.660  0.00  0.00           H  
HETATM    6  H04 UNK     1      -0.861   0.330  -0.581  0.00  0.00           H  
HETATM    7  H05 UNK     1       0.422  -1.341  -1.381  0.00  0.00           H  
HETATM    8  H06 UNK     1      -0.263  -0.021   1.058  0.00  0.00           H  
HETATM    9  O01 UNK     1       1.513   1.598   1.022  0.00  0.00           O  
HETATM   10  O02 UNK     1       0.385  -1.311  -0.422  0.00  0.00           O  
CONECT    1    2    6    8   10
CONECT    2    1    3    4    9
CONECT    3    2
CONECT    4    2
CONECT    5    9
CONECT    6    1
CONECT    7   10
CONECT    8    1
CONECT    9    2    5
CONECT   10    1    7
END

my surface .xyz files:  [surface_xyzfiles.zip](https://github.com/RagnarB83/ash/files/15131746/surface_xyzfiles.zip)

**Comment by RagnarB83** [comment]
Hi, thanks for trying out the program.
I was able to reproduce this and get the same thing.
It's not a bug, it's just that these kind of scans are trickier than one might think for molecules with more than a few atoms.
If you compare the -50 and +50 point geometries you find that the program did what you asked, it performed constrained optimizations for the points with dihedral values of -50 or +50 constrained respectively. But the geometry is slightly different, when one would expect it to be symmetrical:  the -50 point results in a different geometry than the +50 one when you compare the OH...OH interactions.
What's happened is that the +50 point is stuck in a local minimum with two 2.55 Å O...H hydrogen bond interactions while -50 point found a lower energy minimum by a better orientation of the H-atoms (giving a more favorable 2.2 Å H-bond).
If you do regular geometry optimizations (without a constraint) starting from the -50 and +50 points respectively you will find that this will also give you 2 different structures respectively, confirming that 2 different minima exists within this region of the energy surface.

While in principle it could be possible to get a relaxed scan like this to follow the lower energy path, in practice it is tricky to achieve automatically, unfortunately, as there is never a guarantee that you don't end up in a local minimum somewhere along the path.

**Comment by Lactoria-cornuta** [comment]
Hello! Thank you for a quick reply and your insight! Will keep this in mind next time I do scanning.
