### ISSUE TITLE
 ASH:MM part of QM/MM

### ISSUE THREAD

**Issue by MilesYyh** [RagnarB83/ash#420]
Hi!
Is ASH use charmm force filed default for MM part during the QM/MM calculation?
Because i use the amber force field with the Gromacs during the molecualr simulation. Is it reasonable to use charmm force filed for the MM part within QM/MM?

**Comment by MilesYyh** [comment]
I made a mistake

**Comment by RagnarB83** [comment]
You can define whatever forcefield you want and various file-format options are possible, but it would make the most sense to stick with what you have used before. If you have forcefield modifications then you have to ensure they can be define in ASH.
You can try to read in the GROMACS system and FF files directly into ASH, although this option is less tested.

**Comment by MilesYyh** [comment]
Thank for u answer! Actually, I had learned thoroughly the ASH tools from ASH websibe these days. And I found it really convenient to do QM/MM research (especially comparing with using tcl-chemshell) . I will try it more in my research instead of using chemshell package all the times. 

Best wishes for your team.

**Comment by RagnarB83** [comment]
Glad to hear it!
