### ISSUE TITLE
Very good tool, how should I cite it?

### ISSUE THREAD

**Issue by 0xBytefuzz** [RagnarB83/ash#428]
In the paper I collaborated on with Dr. Sun, I used ASH for part of my work, and it was very useful and easy to use. Although I am currently unable to fully utilize ASH's capabilities, I plan to continue learning and using ASH in my research. The paper has been successfully published, and I provided ASH's website and my access time. Meanwhile, I hope there will be a paper describing ASH to help more people learn about it!"🤗🤗🤗 

Thank you very much for answering many of my questions about ASH in the past; your enthusiasm has inspired me! 😊

![1727936651168](https://github.com/user-attachments/assets/f0ad5ab5-d467-4961-9bca-286ab0127ae7)
https://www.nature.com/articles/s41467-024-52613-x

**Comment by RagnarB83** [comment]
Hi great to hear, thanks for the feedback. I am very glad to hear that ASH has been useful for your research and that you will continue to use it.

Yes, being able to cite ASH properly is obviously important. The paper describing ASH is in its final stages and should be submitted this month.

**Comment by 0xBytefuzz** [comment]
Hi Dr. Bjornsson,

Thank you for your message! I'm thrilled to hear that the paper describing ASH is in its final stages and will be submitted soon. Properly citing ASH is indeed crucial, and I'm looking forward to having the reference available.

Best regards,
Gen Lu
