### ISSUE TITLE
How to run Multiple metadynamics simulations

### ISSUE THREAD

**Issue by Zuttergutao** [RagnarB83/ash#430]
Recently, I’ve been learning to use ASH by going through the tutorials. In the tutorial “Single-CV Metadynamics on n-Butane”, the method “Multiple Metadynamics Simulations” is mentioned, but I couldn’t find any code examples on how to implement it. Could you provide me with some guidance?

**Comment by RagnarB83** [comment]
Hi, good point, it was not particularly clear.
There is now an example here:
https://ash.readthedocs.io/en/latest/Biased-sampling.html

**Comment by Zuttergutao** [comment]
Thank you so much, RagnarB83! 
Additionally, the required files mentioned in the tutorial, such as 3fgaba.xyz and butane.xyz, are not provided. After checking the repository, I noticed that several input files are missing.

**Comment by RagnarB83** [comment]
Good point. butane.xyz is already available in the database (so Fragment(databasefile="butane.xyz") will work on its own), but I have now added it to the examples directory. 3fgaba.xyz was missing and I have added it and some other files as well. 

See commits in NEW branch: https://github.com/RagnarB83/ash/commit/4e57b51c42adc3f3386d3d41df8052d64781794b

**Comment by Zuttergutao** [comment]
Thanks！It works well！
