### ISSUE TITLE
Strange bug with xtb and solvent

### ISSUE THREAD

**Issue by quanp** [RagnarB83/ash#437]
Hi RagnarB83,

I am testing a calculation with xtb, but I encountered a strange behavior when using implicit solvent. Apparently, I saw that it was not taken into account in the total energy. I am not sure if it is a bug with xtb or ASH. Strangely enough, in xtb_.out file, I can see
`program call               : xtb xtb_.xyz --alpb H2O --gfn 2 --chrg 0 --uhf 0 --iterations 500 --etemp 300 --acc 0.1 --parallel 1 --input xtbinput`

Re-running this call interactively gives the correct energy.

```
from ash import *

react=Fragment(xyzfile="react.xyz", charge=0, mult=1)

xtbcalc = xTBTheory(xtbmethod='GFN2', solvent="H2O")

Singlepoint(theory=xtbcalc, fragment=react)
```

Thanks
[opt.log.txt](https://github.com/user-attachments/files/17536735/opt.log.txt)
[xtb_.out.txt](https://github.com/user-attachments/files/17536736/xtb_.out.txt)
[react.xyz.txt](https://github.com/user-attachments/files/17536737/react.xyz.txt)

**Comment by RagnarB83** [comment]
Hi Quan, thanks for spotting.
Yes, you are right, this is a bug in ASH. A bit dependent on the behaviour of the shell but a bug nonetheless.
I have fixed it in both NEW and master branches.
Can you run it again and confirm?

**Comment by quanp** [comment]
Thanks. The bug is solved.
