### ISSUE TITLE
QMMM Metadynamics using QM atoms in the CVs

### ISSUE THREAD

**Issue by miqueleg** [RagnarB83/ash#444]
Hello,

I'm working on a protein system that has a MM using Amber 14 FF and xTB GNF2 for some atoms on the Active site and substrates.
I plan to use the metadynamics (like it can be done in other software like CP2K) to explore the FEL of the reaction, and to do so, I used 2 atom distances are CVs. 
```python
from ash import *

##Cores to use for QM-program (and MM-program if platform='CPU')
numcores=8
##MM-platform options: 'CPU', 'OpenCL', 'CUDA'
MM_platform='CUDA'

biasdir="/home/miqueleg/QMMM/PROT/QMMMMD/test1/bias2"

##PDB-file and fragment
frag=Fragment(amber_prmtopfile='PROT_QMMM.prmtop', pdbfile='frag-minimized.pdb')

##MM-theory object
openmmobj = OpenMMTheory(Amberfiles=True, amberprmtopfile="PROT_QMMM.prmtop", fragment=frag, platform='CUDA')

##QM-theory object
xTBobj = xTBTheory(xtbmethod='GFN2',numcores=numcores)

##QM-region definition
SUB1=list(range(15457-1, 15466))
SUB2=list(range(15470-1,15472))
CATTYR=list(range(2204-1,2210))
CATSER=list(range(2003-1,2007))
TYR=list(range(166-1,172))
T3P=list(range(15467-1,15459))
qmatoms = SUB1+SUB2+CATTYR+CATSER+TYR+T3P

##QM/MM object
qm_mm = QMMMTheory(qm_theory=xTBobj, mm_theory=openmmobj, fragment=frag,
        qmatoms=qmatoms, printlevel=2, qm_charge=-1, qm_mult=1, unusualboundary=True)

OpenMM_metadynamics(fragment=frag, theory=qm_mm, timestep=0.001,
            simulation_time=5, printlevel=0, enforcePeriodicBox=False,
            traj_frequency=10, temperature=300, integrator='LangevinMiddleIntegrator',
            CV1_type="distance", CV1_atoms=[2207,15453],
            CV2_type="distance", CV2_atoms=[15453,15457],
            CV1_range=[0.9,2.4], CV2_range=[1,3.0],
            biasfactor=6, height=1,
            CV1_biaswidth=0.01, CV2_biaswidth=0.01,
            frequency=10, savefrequency=10,
            biasdir=biasdir)

``` 

The output bias I have are infinitesimal numbers that are rounded to 0, But I see no error in the output.
Does ASH support the use of CVs from the QM region, in order to describe a reaction happening in a QMMM system?

ASH Output metadynamics:
```
                        ###############################
                        #                             #
                        #     OpenMM metadynamics     #
                        #                             #
                        ###############################
biasdirectory chosen to be: /home/miqueleg/QMMM/PROT/QMMMMD/test1/bias2
Full path to biasdirectory is: /home/miqueleg/QMMM/PROT/QMMMMD/test1/bias2
Using OpenMM built-in metadynamics option (use_plumed=False)

[SOME QMMM stuff with no errors]

----------------------------------------------------------------------------------
Time to calculate step (update custom external force): 0.036 seconds, 0.0 minutes.
----------------------------------------------------------------------------------
Now calling OpenMM native metadynamics and taking 1 step


``` 

The system does not crash, but I do not have a propper metadynamics FEL.

Bias values at the end:

```
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [5.42345687e-199 2.85959950e-197 1.44786641e-195 ... 2.75889473e-103
  1.58510979e-103 8.74536271e-104]
 [5.19835629e-197 2.74091182e-195 1.38777272e-193 ... 2.05176815e-101
  1.17883359e-101 6.50385695e-102]
 [4.78529907e-195 2.52312116e-193 1.27750141e-191 ... 1.46546223e-099
  8.41974325e-100 4.64533808e-100]]
```

**Comment by RagnarB83** [comment]
Yes, this should all have worked.
Have you tried first running a regular QM/MM molecular dynamics job ?

I'm not quite sure where things might have gone wrong at first glance, can you share the files so that I can try to reproduce this?

**Comment by miqueleg** [comment]
I did not tried with a QMMM job first, I'll try in a bit.

Find the inputs attached, I hope is just a user error by my site.
[IN_files.zip](https://github.com/user-attachments/files/18062589/IN_files.zip)

**Comment by miqueleg** [comment]
I did the QMMM MD, and everything seems fine.
Looking at the trajectory dcd from the metadynamics, it seems like there is some problem in setting up the box shape, but this does not happens using the non-metadynamics QMMM MD. Maybe only cubical box is possible using this method?
![Waterbox](https://github.com/user-attachments/assets/efea07e7-c765-49ec-ad8f-c6c4db43a8ac)

I do not know, this still does not seem to explain the energy going to 0 in all frames. Maybe because the bias is going into reshaping the box? IDK. I'll try to make a cubic box and re-send soon.

**Comment by RagnarB83** [comment]
So number one issue is that you do have to enable the periodic boundary conditions first or you will describe the system nonperiodically (and waters will start to evaporate):

`openmmobj = OpenMMTheory(Amberfiles=True, amberprmtopfile="PROT_QMMM.prmtop", fragment=frag, platform=MM_platform, periodic=True)`

You also need to set enforcePeriodicBox=True in both the MolecularDynamics and OpenMM_metadynamics functions as the ASH wrapping procedure that is otherwise active can only handle cubic boxes.

**Comment by RagnarB83** [comment]
I don't think the atom indices in CV1_atoms and CV2_atoms lists are correct. When I visualized them in VMD the atoms in each atompair were quite far apart. Atom-indexing issue ? Atom 15453 is not in the QM-region actually according to the QM-region definition.

**Comment by miqueleg** [comment]
On one hand, Regarding the Periodic boundary conditions. Yes, my bad, I'm used to work using the inpcrd from amber that has that information in the input and I forgot to add this here working from a minimized pdb.

On the other hand, you are right, the CV atoms are not correct regarding the output, but are right looking at the atom-id from the input pdb. I guess this is regarding the python ordering (start with 0) instead of the pdb (start with 1). It is a bit annoying, but not a problem.

ASH out:
```
                            ########################
                            #                      #
                            #     QM/MM Theory     #
                            #                      #
                            ########################
QM-theory: xTBTheory
MM-theory: OpenMMTheory
All atoms in fragment: 94672
QM region (32 atoms): [165, 166, 167, 168, 169, 170, 171, 2002, 2003, 2004, 2005, 2006, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 15456, 15457, 15458, 15459, 15460, 15461, 15462, 15463, 15464, 15465, 15469, 15470, 15471]
MM region (94640 atoms)
QM/MM object selected to use 8 cores
Embedding: elstat
No atomcharges list passed to QMMMTheory object
Getting system charges from OpenMM object
Truncated PC approximation in QM/MM is active.
TruncPCRadius: 35
TruncPC Recalculation iteration: 50
QM-region coordinates (before linkatoms):
15469    N  34.29100000   41.15600000   41.00700000
15470    N  34.55400000   42.61000000   41.02700000
15471    N  34.84400000   44.05800000   41.05400000
``` 
PDB: 
``` 
HETATM15470  N01 AZI A1011      56.675  60.665  31.580  1.00  0.00           N
HETATM15471  N02 AZI A1011      55.441  60.860  32.375  1.00  0.00           N
HETATM15472  N03 AZI A1011      54.205  61.041  33.169  1.00  0.00           N
``` 

Whatever, I'll make this changes and let you know if it works as intended.
Thanks a lot.

**Comment by miqueleg** [comment]
Still working on it, but I have it working.

Thanks a lot
![MTD_CV1_CV2_](https://github.com/user-attachments/assets/0bf1a91c-a893-4581-b24e-a4d6d07d621c)

**Comment by RagnarB83** [comment]
OK great, glad to hear it.
