### ISSUE TITLE
getwaterconstraintslist returns empty list

### ISSUE THREAD

**Issue by quanp** [RagnarB83/ash#445]
Hi RagnarB83,

I am trying to follow the tutorial of Rubredoxin. It seems that the getwaterconstraintslist function returns an empty list. Is this behavior expected? Print ommtheoryobject shows:

```
    print("Length of Atom types:", len(openmmtheoryobject.atomtypes))
    print("Length of Residue names:", len(openmmtheoryobject.resnames))
    print("Length of Elements:", len(openmmtheoryobject.mm_elements))
    print("Number of atoms:", openmmtheoryobject.numatoms)

```
```
Inside getwaterconstraintslist
Length of Atom types: 0
Length of Residue names: 16027
Length of Elements: 0
Number of atoms: 16027
```

https://github.com/RagnarB83/ash/blob/master/examples/OpenMM_Modeller-setups/rubredoxin/4-QM_MM-Optimization/4-QMMM_Opt-bigact.py

**Comment by RagnarB83** [comment]
Yeah, that was a bug in the getwaterconstraintslist function as well as a missing attribute defintion in OpenMMTheory.
Has now been fixed in the NEW branch.
Thanks for reporting.

**Comment by quanp** [comment]
Thank you very much. It is now fixed.
